### ISSUE TITLE
loading error on start-up

### ISSUE THREAD

**Issue by gbdomubpkm** [nicolascolla/simple-reader#1]
Hello  🙂. Thanks for this app but :

Volla phone OTA-19 
![screenshot20211111_170913710](https://user-images.githubusercontent.com/50362604/141333373-0972eb3b-b399-449f-9729-bf567922dd3e.png)
Reload change nothing

Moreover, the blue  link 'report an issue' go towards
https://github.com/geek1011/ePubViewer/issues

**Comment by cibersheep** [comment]
Same for Meizu X4 on RC

**Comment by nicolascolla** [comment]
@gbdomubpkm @cibersheep, is this bug also found in ePubViewer (https://open-store.io/app/net.gsantner.ut.epubviewer)?

It happens to me when I open the index.html with a desktop browser like Firefox. On my Redmi Note 9, however, it works fine.

**Comment by nicolascolla** [comment]
This commit is the culprit: https://github.com/nicolascolla/simple-reader/commit/a75cc2a6cb4366178887430244ff06019bf0e53c

This app is very broken as it is, so I will remove it from the store for now.

**Comment by nicolascolla** [comment]
This turned out to be a very stupid bug. I forgot to set a default font for the rendering engine, so the app threw an error.

It is fixed and I have pushed an update. Hopefully it works for everyone now. If you get a double icon, you might have to uninstall and reinstall in order to delete the second one.

**Comment by gbdomubpkm** [comment]
Thanks that's ok. 
The app has no support (yet only ?) for DRM protected e-book ? Isn't it ?

**Comment by nicolascolla** [comment]
> Thanks that's ok. The app has no support (yet only ?) for DRM protected e-book ? Isn't it ?

Only regular, non-DRMed ePub files are supported. DRM-protected ebooks are a totally different beast so I don't think they will ever be supported. I recommend stripping the DRM with Calibre (if your local legislation allows it), even if your reader app supports DRM.

This is the fork of a fork and I haven't looked much into the rendering engine. I am more interested in interface improvements. But support for formats similar to ePub, like mobi or azw3, might be added as time (and knowledge) allows.
